spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/match
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  docker:
    compose:
      file: ./local/docker-compose.yml