package nl.kooi.match.core.enums;

public enum ResponseType {
    PROCESSED_SUCCESSFULLY,
    PLAYER_NOT_ACTIVE_IN_MATCH,
    ALREADY_HAD_A_YELLOW_CARD,
    LINE_UP_NOT_ALLOWED,
    MATCH_NOT_FOUND,
    PROCESSED_UNSUCCESSFULLY,
    MATCH_NOT_ACTIVE,
    MATCH_REQUESTED_FOR_NON_EXISTING_TEAM
}
